language: php

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

## Install or update dependencies
install:
  - composer install

## Run the actual test
script:
  - php tests/test.php
